import type { Reporter } from './index';
import type { ScanResult, ScanSummary } from '../types';

const LEVEL_ICON: Record<string, string> = {
  high: '🔴 HIGH',
  medium: '🟡 MEDIUM',
  low: '🔵 LOW',
};

export class MarkdownReporter implements Reporter {
  report(results: ScanResult[], summary: ScanSummary): void {
    const lines: string[] = [];

    lines.push('## nestjs-leak-guard Scan Results\n');

    if (results.length === 0) {
      lines.push('✅ **No issues found.**\n');
    } else {
      const n = summary.issues;
      lines.push(
        `Found **${n} issue${n !== 1 ? 's' : ''}** across ${summary.files} file${summary.files !== 1 ? 's' : ''} (${summary.durationMs}ms)\n`,
      );

      lines.push('| Level | File | Line | Pattern | Message |');
      lines.push('|-------|------|------|---------|---------|');

      for (const r of results) {
        const shortFile = r.file.replace(/^.*\/src\//, 'src/');
        lines.push(
          `| ${LEVEL_ICON[r.level] ?? r.level.toUpperCase()} | \`${shortFile}\` | ${r.line} | \`${r.pattern}\` | ${r.message} |`,
        );
      }

      lines.push('\n### Details\n');
      for (const r of results) {
        lines.push(`#### \`${r.pattern}\` — \`${r.file}:${r.line}\``);
        lines.push(`- **Level:** ${r.level}`);
        lines.push(`- **Code:** \`${r.code.replace(/`/g, "'")}\``);
        lines.push(`- **Fix:** ${r.suggestion}`);
        lines.push(`- **Docs:** <${r.docsUrl}>\n`);
      }
    }

    lines.push(
      `\n---\n_Generated by [nestjs-leak-guard](https://github.com/jinyeong-jung/nestjs-leak-guard) · ${summary.durationMs}ms_`,
    );

    process.stdout.write(lines.join('\n') + '\n');
  }
}
